### ISSUE TITLE
Cut version 12.0.0 alpha for client

### ISSUE THREAD

**Issue by palnabarun** [kubernetes-client/python#1052]
Kubernetes Python client v12.0.0 would track Kubernetes v1.16

### Tasks

- [x] Cut 12.0.0 snapshot branch
- [x] Upgrade openapi-generator version
- [x] Drop Python 2 support
> To be updated

**Comment by scottilee** [comment]
Update -- since Roy is out I am trying to sync up with @yliaog on this, who I pinged on Slack.

**Comment by justaugustus** [comment]
@yliaog @roycaihw @scottilee @palnabarun -- Any update on getting a release for this --> https://github.com/kubernetes-client/python/pull/1088?
Kubernetes 1.18.0 is being released today, which means 1.15 will no longer be supported very soon.

**Comment by yliaog** [comment]
i think @scottilee is working on it, any update @scottilee ?

**Comment by palnabarun** [comment]
@justaugustus The release of a v1.16 based client should be done soon.

@scottilee Let us know if you are blocked on anything.

**Comment by scottilee** [comment]
Yep, I'll take a look tonight and tomorrow.

**Comment by justaugustus** [comment]
Thanks for the updates!

**Comment by booooh** [comment]
@scottilee Is this still planned? I see that #1141 has been merged

**Comment by thomasjo** [comment]
Is there anything we can help out with to get this ball rolling again?

**Comment by scottilee** [comment]
Hey guys, this is still planned. Should have more updates later this week.

**Comment by LouisPlisso** [comment]
hi @palnabarun any update???

**Comment by gopinatht** [comment]
What can we do help speed up support for more recent versions of Kubernetes?

**Comment by torgeirl** [comment]
> What can we do help speed up support for more recent versions of Kubernetes?

I don't believe it has been communicated here so I'll echo what @palnabarun mentioned in the Kubernetes Slack's `#kubernetes-client` channel on June 9: «We are blocked by some issues with the generator and the upstream OpenAPI spec». It seems to be underway in #1188, updated as late as yesterday. :crossed_fingers:

**Comment by torgeirl** [comment]
Seems like the release of `12.0.0a1` just got approved (#1217)! 🎉

**Comment by palnabarun** [comment]
The Kubernetes Python Client 12.0.0a1 was released vide #1217. Hence, closing this issue.

/close
